### ISSUE TITLE
Node Manager点击之后，页面一直处于加载之中，无法显示

### ISSUE THREAD

**Issue by string2020** [xiaolongzuo/niubi-job#15]
后台也报错了
2016 Apr 12 17:35:51  INFO [LeaderSelector-0] - 127.0.0.1 is now the leader ,and has been leader 4184 time(s) before.
2016 Apr 12 17:35:51  INFO [LeaderSelector-0] - job cache has been closed.
2016 Apr 12 17:35:51  INFO [LeaderSelector-0] - begin stop scheduler manager.
2016 Apr 12 17:35:51  INFO [LeaderSelector-0] - 127.0.0.1 has been shutdown. [Data{ip='127.0.0.1', state='Backup', runningJobCount=0}]
2016 Apr 12 17:35:51  INFO [LeaderSelector-0] - clear node successfully.
2016 Apr 12 17:35:51  WARN [LeaderSelector-0] - 127.0.0.1 startup failed,relinquish leadership.
java.lang.NullPointerException
	at com.zuoxiaolong.niubi.job.api.curator.StandbyJobApiImpl.getAllJobs(StandbyJobApiImpl.java:42)
	at com.zuoxiaolong.niubi.job.cluster.node.StandbyNode$StandbyLeadershipSelectorListener.startupJobs(StandbyNode.java:158)
	at com.zuoxiaolong.niubi.job.cluster.node.StandbyNode$StandbyLeadershipSelectorListener.acquireLeadership(StandbyNode.java:149)
	at com.zuoxiaolong.niubi.job.cluster.node.AbstractClusterJobNode$AbstractLeadershipSelectorListener.takeLeadership(AbstractClusterJobNode.java:106)
	at org.apache.curator.framework.recipes.leader.LeaderSelector$WrappedListener.takeLeadership(LeaderSelector.java:536)
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:399)
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:443)
	at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:64)
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:245)
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:239)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)^C

**Comment by xiaolongzuo** [comment]
重新readme文件当中的地址下载安装包即可，问题已修复。如果你解决了问题，很期待你能反馈在这里。
