### ISSUE TITLE
下载了niubi-job-0.9.6.x这个版本部署一直报错

### ISSUE THREAD

**Issue by liangruiwei** [xiaolongzuo/niubi-job#23]
您好，我下载了最新的下载niubi-job-0.9.6.x这个版本部署后，从console上传了LZ的个人网站上下载的niubi-job-sample-common.jar，niubi-job-sample-spring.jar包。点击execute后，一直启动不了job，一直fail，其余的部署都正常，后台报错一直提示
2016 九月 25 22:10:37 ERROR [PathChildrenCache-0] - handle operation failed. Job
Data {groupName='com.zuoxiaolong.niubi.job.sample.spring.job.Job2', jobName='tes
t', jarFileName='niubi-job-sample-spring.jar', packagesToScan='com.zuoxiaolong',
 jobCron='0/15 \* \* \* \* ?', containerType='Spring', jobState='Shutdown', misfireP
olicy='None', jobOperationLogId='2d8193c9-d967-48ba-bd8b-9537f9e8c8bf', operatio
nResult='Waiting', originalJarFileName='niubi-job-sample-spring.jar', jobOperati
on='Start', version=20, errorMessage='null'}
com.zuoxiaolong.niubi.job.core.exception.NiubiException: java.lang.ClassNotFound
Exception
        at com.zuoxiaolong.niubi.job.scheduler.DefaultManualScheduleManager.star
tupManual(DefaultManualScheduleManager.java:60)
        at com.zuoxiaolong.niubi.job.cluster.node.MasterSlaveNode$JobCacheListen
er.executeOperation(MasterSlaveNode.java:355)
        at com.zuoxiaolong.niubi.job.cluster.node.MasterSlaveNode$JobCacheListen
er.childEvent(MasterSlaveNode.java:331)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(
PathChildrenCache.java:516)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(
PathChildrenCache.java:510)
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerC
ontainer.java:92)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorSer
vice.execute(MoreExecutors.java:297)
        at org.apache.curator.framework.listen.ListenerContainer.forEach(Listene
rContainer.java:83)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache.callList
eners(PathChildrenCache.java:507)
        at org.apache.curator.framework.recipes.cache.EventOperation.invoke(Even
tOperation.java:35)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$9.run(Pa
thChildrenCache.java:759)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException
        at com.zuoxiaolong.niubi.job.scanner.ApplicationClassLoader.loadClass(Ap
plicationClassLoader.java:165)
        at com.zuoxiaolong.niubi.job.scanner.ApplicationClassLoader.loadClass(Ap
plicationClassLoader.java:93)
        at com.zuoxiaolong.niubi.job.scheduler.JobEnvironmentCache.createJobBean
Factory(JobEnvironmentCache.java:140)
        at com.zuoxiaolong.niubi.job.scheduler.JobEnvironmentCache.loadJobEnviro
nment(JobEnvironmentCache.java:116)
        at com.zuoxiaolong.niubi.job.scheduler.DefaultManualScheduleManager.star
tupManual(DefaultManualScheduleManager.java:58)
        ... 17 more
希望你能帮忙看下

**Comment by xiaolongzuo** [comment]
你的包是刚下载的吗。

**Comment by liangruiwei** [comment]
是的额。就这几天下载的，应该是最新的吧 ，不知道为啥一直就是部署报错,我这两天正在学习这个。先学习下。应该能找到原因
